### ISSUE TITLE
Any solution for support the client access from internet (out side of LAN)

### ISSUE THREAD

**Issue by LinhDNguyen** [jcasoft/Web-Chat-Client-for-Mycroft#1]
in main.py, the ip address is the LAN ip address. The code will returns "No IP address" if the last ethernet interface does not have IP (for example, pi3 has lo, eth0, and wlan0. If wlan0 does not have connection, the final 'ip' var will be "No IP addr").

If I access the web client from internet, the javascript code still use my local ip address for websocket connection, so I think we can update the javascript code to get the ip/host name from URL instead of passing it from backend (main.py).

**Comment by LinhDNguyen** [comment]
pull-request #2  was created. Please take a look.

**Comment by jcasoft** [comment]
Fixed with your suggestion, thx.!
